[package]
name = "latte"
description = "Cassandra LATency TEster"
version = "0.1.0"
authors = ["Piotr Kołaczkowski <pkolaczk@datastax.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-counter = "1.0.1"
cassandra-cpp = "0.15.1"
clap = "3.0.0-beta.1"
console = "0.11.2"
cpu-time = "1.0.0"
hdrhistogram = "7.1.0"
indicatif = "0.15.0"
time = "0.1.44"
tokio = { version = "0.2", features = ["full"] }
