[package]
name = "latte"
description = "Cassandra LATency TEster"
version = "0.1.0"
authors = ["Piotr Kołaczkowski <pkolaczk@datastax.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdrs = "2"
clap = "3.0.0-beta.1"

