[package]
name = "latte"
description = "Cassandra Latency and Throughput Tester. Runs CQL queries in parallel, measures performance and computes useful statistics."
version = "0.7.0"
authors = ["Piotr Kołaczkowski <pkolaczk@datastax.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.45"
atomic-counter = "1.0.1"
cassandra-cpp = "0.17.0"
cassandra-cpp-sys = "0.12"
chrono = "0.4.18"
clap = "3.0.0-beta.5"
console = "0.11.2"
cpu-time = "1.0.0"
err-derive = "0.3"
futures = "0.3"
hdrhistogram = "7.1.0"
indicatif = "0.15"
itertools = "0.9"
jemallocator = "0.3.2"
metrohash = "1.0"
num_cpus = "1.13.0"
proc-macro2 = "1.0.32"
rand = "0.7.3"
regex = "1.5.4"
rune = { git = "https://github.com/rune-rs/rune.git", branch = "main" }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
statrs = "0.13.0"
strum = { version = "0.19.5", features = ["derive"] }
strum_macros = "0.19.4"
tokio = { version = "1.11", features = ["full"] }
tokio-stream = "0.1"
time = "0.1.44"
uuid = { version = "0.8", features = ["v4"] }
lazy_static = "1.4.0"

[dev-dependencies]
tokio-test = "0.4.2"

[profile.release]
debug = true